apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    # antaloala changes START
    # name: flux-system
    name: flux2-kustomize-helm-example
    # antaloala changes END
  path: ./infrastructure
  prune: true

